@baseUrl = http://localhost:3000
###
GET {{baseUrl}}/


###
## CRETE TASK
POST {{baseUrl}}/api/v1/tasks
Content-Type: application/json

{
    "id" : 100,
    "task" : "task 1",
    "hour" : 20,
    "type" : "good"
    }


### READ TASK
GET {{baseUrl}}/api/v1/tasks

### Update task
PATCH  {{baseUrl}}/api/v1/tasks/HGpG3P
Content-Type: application/json

{
    "task":  "PATCH TASK 2",
    "hour": 5,
    "type": "good"
}